{% set name = "nglview" %}
{% set version = "3.0.1" %}
{% set sha256 = "845115a126f1a95c4c8907289566d8f47fbee6898a20c71255f601173cf0f553" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nglviewer/nglview/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - jupyter-packaging
    - nodejs
  run:
    - python >=3.6
    - numpy
    - ipywidgets >=7
    - jupyterlab_widgets

test:
  requires:
    - jupyterlab
    - notebook
    - pip
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"
    - pip check

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
