{% set name = "nglview" %}
{% set version = "3.0.7" %}
{% set sha256 = "22f02cef4b66d5dcac1b36dcd1c29d2e292ceee6f959994154305836857e4ef9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - jupyter-packaging
    - versioneer-518
    - nodejs
    - notebook
    - ipywidgets >=7
  run:
    - python >=3.6
    - numpy
    - ipywidgets >=7
    - jupyterlab_widgets

test:
  requires:
    - jupyterlab
    - notebook
    - pip
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"
    - jupyter nbextension list 2>&1 | grep -ie "nglview-js-widgets.*enabled"
    - pip check

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
