{% set name = "nglview" %}
{% set version = "1.0" %}
{% set sha256 = "407a3edb9c0f59a660cd9e77e6f342809b568549dde5cd45d2cfbfe37376732c" %}
{% set minimum_ipywidgets_version = "7" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: python setup.py install --conda --single-version-externally-managed --record record.txt
# we can not use noarch, because pre/post-link scripts for install/uninstall of nbwidgets are not avail then.
#  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    # TODO: version 1.0 of nglview pins to the exact version, remove this constraint in future.
    - ipywidgets =={{ minimum_ipywidgets_version }}
    - notebook
    # TODO: unpin after https://github.com/arose/nglview/issues/726 has been fixed/released.
    - ipykernel <4.7
    # nglview wants ~=3.0.0 (eg. a patch release of 3.0 major)
    - widgetsnbextension <3.1,>3.0

test:
  imports:
    - nglview 
    - notebook

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: 'An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.'
  doc_url: https://arose.github.io/nglview/latest/ 
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
