{% set name = "nglview" %}
{% set version = "4.0" %}
{% set sha256 = "2c0cff2c5b1e2a0a72e3393087ce44ae0308524c5aa5f95357812d3edbc26e83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - numpy
    - jupyter-packaging
    - versioneer-518
    - nodejs
    - notebook >=7
    - ipywidgets >=8
  run:
    - python >={{ python_min }}
    - numpy
    - ipywidgets >=8
    - notebook >=7
    - jupyterlab_widgets

test:
  requires:
    - jupyterlab
    - notebook
    - pip
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"
    - pip check

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
