{% set name = "nglview" %}
{% set version = "1.1.3" %}
{% set sha256 = "7923009420dd6876b5f6d5c9cf13012e7840d187254668ddaf3b63692a6b85d1" %}
{% set minimum_ipywidgets_version = "7" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --conda --single-version-externally-managed --record record.txt
# we can not use noarch, because pre/post-link scripts for install/uninstall of nbwidgets are not avail then.
#  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - ipywidgets >={{ minimum_ipywidgets_version }}
    - notebook
    - ipykernel
    # nglview wants ~=3.0.0 (eg. a patch release of 3.0 major)
    - widgetsnbextension <3.1,>3.0

test:
  imports:
    - nglview 
    - notebook

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: 'An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.'
  doc_url: https://arose.github.io/nglview/latest/ 
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
