{% set name = "nglview" %}
{% set version = "0.6.2.3" %}
{% set sha256 = "e32bd25a10e5e1c9df29ee576fad31c1daa0595d5480793298abdb961fa1a52d" %}
{% set minimum_ipywidgets_version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --conda --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - ipywidgets >={{ minimum_ipywidgets_version }},<6
    - notebook

test:
  imports:
    - nglview 
    - notebook

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: 'An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.'
  doc_url: https://arose.github.io/nglview/latest/ 
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
