{% set name = "nglview" %}
{% set version = "2.7.4" %}
{% set sha256 = "d1ee290c2bf733902284e8e4dd9d33fa6216ec55afe3e22d9f45522e60b71b66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: |
    python -m pip install --no-deps --ignore-installed --install-option="--conda" . ;
    jupyter-nbextension install nglview --py --sys-prefix ;
    jupyter-nbextension enable nglview --py --sys-prefix
  noarch: python

requirements:
  build:
    - python >=3
    - pip
    - numpy
    - ipywidgets >=7
    - notebook
  run:
    - python >=3
    - numpy
    - ipywidgets >=7
    - notebook

test:
  imports:
    - nglview

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
