{% set name = "nglview" %}
{% set version = "3.0.0" %}
{% set sha256 = "de0d2e075519a8849f2511aa381100263b646aea3472cb785c33813b5d0f650d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nglviewer/nglview/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - ipywidgets >=7
    - jupyterlab
    - jupyterlab_widgets
    - jupyter-packaging
    - nodejs
    - notebook
  run:
    - python >=3.6
    - numpy
    - ipywidgets >=7
    - notebook
    - jupyterlab_widgets

test:
  requires:
    - jupyterlab
    - notebook
    - pip
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"
    - pip check

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
