{% set name = "nglview" %}
{% set version = "2.7.8" %}
{% set sha256 = "fd84e20f0c1e183f2c429509c4a64b226e8591253545358062f48f3ec7dafddb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nglviewer/nglview/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - ipywidgets >=7
    - jupyterlab
    - jupyterlab_widgets
    - jupyter-packaging
    - nodejs
    - notebook
  run:
    - python >=3.6
    - numpy
    - ipywidgets >=7

test:
  requires:
    - jupyterlab
    - notebook
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
