{% set name = "nglview" %}
{% set version = "2.7.7.dev0" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ericpre/nglview/archive/refs/heads/master.zip
  sha256: dd16527c49e67cdd53b345768da2ba421a04d5cdfd85d1e373260482baa566fd

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - ipywidgets >=7
    - jupyterlab
    - jupyterlab_widgets
    - jupyter-packaging
    - nodejs
    - notebook
    - numpy
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7
    - python >=3.6
    - numpy

test:
  requires:
    - jupyterlab
    - notebook
  imports:
    - nglview
  commands:
    - jupyter labextension list 2>&1 | grep -ie "nglview-js-widgets.*OK"

about:
  home: http://github.com/arose/nglview
  license: MIT
  license_file: LICENSE
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
  doc_url: https://arose.github.io/nglview/latest/
  dev_url: https://github.com/arose/nglview

extra:
  recipe-maintainers:
    - marscher
    - gph82
    - hainm
