travis:
  secure:
    BINSTAR_TOKEN: d7je5FGn9aKVky5LvKhLWJTgjWMXKjHbe3RGh+V1iMsiyYJGnDfK7Tm+U84huhbR35dt6aiA01J7BJJzQMx5N/P12ICsdXIfxmTXnw5ztvBk4Zpdd5Mcj1ilUyO2zvDcfvffG4EflfPKdQrOhkZj1uaO6bJvi47R3ciM1RbF8JWjmZfTvXSB6T8lznP/TJEEXGZaGOPVmzwJCcyD7Yc8SKKhvmEG74qQyDQxWHYvFFH7l8uWrqrZHSl5+5pE+jCBtfp7RqaLXD2OZvvHamU/PkSyIKXSr/MSyw64Zk1AcZMSp41i97SUfgaBL2L99cegpoMPrpwwWSH4aSH11wO7RgNS1bUsp/GxCHnx2rcAG6CFeYCddAzAN0QYPBrbYr1V1bJhHgPsDleV7sa9H7ldCYvAtkcDWnpP8REQCC67gHx/rjNT+YGQYOW0ZvVia9LvsgSmuMnbDt0u81Q/lHqQshw7yVmsOOMWaQ76xprwLJr2iHO+t1Q+Xeu0cwI6eZsd4dlomH1P4jJPHVBFNc1T1I2aYgKXXOtvZSWTPV1ScOzHEot0Zw9IY4OPU+of0ZyRCzQZk9hU+NXLPz+eMtdiqDjLgHBy7gK91c/JtySX3Ic5fcvfFKUQJVz3d+WSSTeAdL/0Cr4YqzSUJ9MgWmBHsYQlUoK7mDl/hs5orZxgkDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
