travis:
  secure:
    BINSTAR_TOKEN: YKGfq3GSERr0Fhy1NHJUzPkzruSvKe/L2KgYAAIYYiAr5S4BoG1eWFCFO2R8MN9Xe3ocsGSSuEy78UH2B9EaS2nFHJVyMQgNEkNFutTFTDMbP4YLEpjvyJaHYh/IoLQVH1OPra9vyKSfz5XNlrIYHhixQ18DLI5O4JxfgjU8Xd48KEPVE/hSjh6fVCah41c3nRRFBWSK6uJDnNhKi7Mm6RphWurtVbbabDL+SnLhch9ew2PzaLVaqEHj9TOaT9Ubjg0QJbGqLRgFJG7MH3Y1yxu637Knmt5jhQxi8uhrWirs5aA1Xx6YJsLFpc6QQHpOj1fBLwUdyVVQm+BjX428EMMqS2C2tf0a63KHJesNC+uzwAqwB3q6LxlQqnbb3pdrHq1WeFmx/801bhBeFV5/Eh0gG/zqZt5vLJhmju8KXPqu4+Wudx5wgxQumQruop04GXpOnN7sZzT/rzT2lvAyZ8VIz4bHkSMSVGhomf+728B+i40ave2YWDFMknqIvUXF6cEZO51pkzsjtTN86HHjiFHLT5xEftuXYwbB3mwI/rQsW71uBuJ0hPrmwNXqgh2sUayhdVUJp6Wc+GIOr8l6m2ot7828Mbv1LZ9sSUmsfdcT+EGlXaIW5W60b2R+FFV4eTA4qZEhkQlmgAmlElwGwwy6OyclEE8JJTq1tI7isX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
